name: Behave Tests
on:
  push:
    branches: ["main"]
jobs:
  behave-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install behave==1.2.6 selenium==3.141.0 urllib3==1.26.15 behave-webdriver

      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Run Behave isitchristmas
        working-directory: isitchristmas
        run: behave
        continue-on-error: true

      - name: Run Behave peppers-ghost
        working-directory: peppers-ghost
        run: behave
        continue-on-error: true

      - name: Run Behave time
        working-directory: time
        run: behave
        continue-on-error: true

      - name: Run Behave primes
        working-directory: primes
        run: behave
        continue-on-error: true